name: Depoy base branch to IPFS

on:
  push:
    branches:
      - base

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build and optimize the code
        run: yarn build

      - name: Export production ready code
        run: yarn export

      - name: Delivery with Pinata
        uses: aquiladev/ipfs-action@v1
        id: pinata
        with:
          path: ./out
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: colkito.xyz

      - name: Update Cloudflare DNS
        uses: wei/curl@v1.1.1
        id: cloudflare
        with:
          args: -X PUT 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.CLOUDFLARE_RECORD_ID }}' -H 'Authorization:Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' -H 'Content-Type:application/json' -d '{\"type\":\"TXT\",\"name\":\"_dnslink\",\"content\":\"dnslink=/ipfs/${{ steps.pinata.outputs.hash }}\",\"ttl\":120,\"proxied\":false}'
