name: Deploy main branch to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy-ipfs:
    name: Deploy to IPFS
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build and optimize the code
        run: hugo -D --minify

      - name: Upload to IPFS with Pinata
        uses: aquiladev/ipfs-action@v0.3.1
        id: pinata
        with:
          path: ./public
          service: pinata
          pinName: ${{ secrets.PIN_NAME || github.event.repository.name }}
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
