name: Deploy main branch to IPFS

on:
  push:
    branches:
      - ipfs

jobs:
  deploy:
    name: Deploy to IPFS
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and optimize the code
        run: npm run build

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          # extended: true

      - name: Build and optimize the code
        run: hugo -D --minify

      - name: Upload to IPFS with Pinata
        uses: aquiladev/ipfs-action@v0.3.1
        id: pinata
        with:
          path: ./public
          service: pinata
          pinName: ${{ secrets.PIN_NAME || github.event.repository.name }}
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}

      - name: Update Cloudflare DNS
        uses: wei/curl@v1.1.1
        id: cloudflare
        with:
          args: -X PUT 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.CLOUDFLARE_RECORD_ID }}' -H 'Authorization:Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' -H 'Content-Type:application/json' -d '{\"type\":\"TXT\",\"name\":\"_dnslink\",\"content\":\"dnslink=/ipfs/${{ steps.pinata.outputs.hash }}\",\"ttl\":1,\"proxied\":false}'
